### ISSUE TITLE
Shade Group Issue

### ISSUE THREAD

**Issue by peterxrock** [danaues/pylutron-caseta#14]
Hello. After 2022.11, I noticed that commands to shade groups aren't being honored through the integration. They work normally through the Lutron app. When I close/open a shade group, one of the shades will move briefly then stop. It fails 100% of the time, so it's easily reproducible. 

[config_entry-lutron_caseta-4ce99760b8abb50e7f5c7e1380cb22d8.json.txt](https://github.com/danaues/pylutron-caseta/files/10188456/config_entry-lutron_caseta-4ce99760b8abb50e7f5c7e1380cb22d8.json.txt)

**Comment by peterxrock** [comment]
Have been troubleshooting a little more. If I delete the device from the integration, then reload it, it works for about a day then stops working again. I'm also seeing it happen when multiple shades are called to close - one or two don't respond (some are part of groups, some are not) so maybe it's just a queuing issue?

**Comment by peterxrock** [comment]
@danaues Any chance to take a look?

**Comment by peterxrock** [comment]
Abandoning this integration since shades don’t work.

**Comment by danaues** [comment]
Unfortunately, I don't have any shades in my install.  I don't have any way of troubleshooting or digging into this issue.
